show=drun
prompt=Search apps
width=46%
height=52%
location=center
allow_images=true
image_size=36
columns=1
no_actions=true
hide_scroll=true
matching=fuzzy
insensitive=true
sort_order=alphabetical
gtk_dark=true
