source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/monitor-layout.conf
source = ~/.config/hypr/hyprsplit.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/windows.conf

$mainMod = SUPER
$terminal = kitty
$fileManager = nautilus
$menu = ~/.config/hypr/scripts/launch-apps.sh

$browser = xdg-open https://start.duckduckgo.com

source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/autostart.conf
