input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options = compose:caps
    kb_rules =
    follow_mouse = 1
    sensitivity = 0

    touchpad {
        tap-to-click = true
        natural_scroll = false
    }
}

gesture = 3, horizontal, workspace
